<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE event [<!ELEMENT zip_code (#PCDATA)><!ELEMENT url_link_display (#PCDATA)><!ELEMENT url (#PCDATA)><!ELEMENT tracks (track+)><!ELEMENT track (#PCDATA)><!ELEMENT title (#PCDATA)><!ELEMENT timeslot (slot_id?, event_id?, title, room, date, start_time, end_date?, end_time, description?, acm_doi?, persons?, tracks?, tags?)><!ELEMENT tags (tag+)><!ELEMENT tag (#PCDATA)><!ELEMENT suffix (#PCDATA)><!ELEMENT subevent_logo_url (#PCDATA)><!ELEMENT subevent_id (#PCDATA)><!ELEMENT subevent (subevent_id?, title, acronym?, subevent_type, description?, room, date, url?, url_link_display?, subevent_logo_url?, acm_doi?, persons?, tracks?, tags?, sponsor?, timeslot*)><!ELEMENT state (#PCDATA)><!ELEMENT start_time (#PCDATA)><!ELEMENT start_date (#PCDATA)><!ELEMENT sponsor (#PCDATA)><!ELEMENT sort_key (#PCDATA)><!ELEMENT slot_id (#PCDATA)><!ELEMENT subevent_type EMPTY><!ATTLIST subevent_type	type (case_study | demonstration | poster | regular | tutorial | workshop) #IMPLIED><!ELEMENT room (#PCDATA)><!ELEMENT role (#PCDATA)><!ELEMENT picture_url (#PCDATA)><!ELEMENT persons (person+)><!ELEMENT person (role, sort_key, first_name, middle_name?, last_name, suffix?, affiliation, acm_profile_id?, email?, bio?, homepage_url?, picture_url?, person_id?)><!ELEMENT middle_name (#PCDATA)><!ELEMENT location (facility_name, facility_map_url?, address, city, state?, country, zip_code?)><!ELEMENT last_name (#PCDATA)><!ELEMENT homepage_url (#PCDATA)><!ELEMENT first_name (#PCDATA)><!ELEMENT facility_name (#PCDATA)><!ELEMENT facility_map_url (#PCDATA)><!ELEMENT event_type EMPTY><!ATTLIST event_type	type (conference|workshop|symposium) #IMPLIED><!ELEMENT event (event_details, subevent*, timeslot*, timezone_id?)><!ELEMENT event_logo_url (#PCDATA)><!ELEMENT event_details (title, acronym, event_type, start_date, end_date, location, description, url?, url_link_display?, event_logo_url?, persons?)><!ELEMENT end_time (#PCDATA)><!ELEMENT end_date (#PCDATA)><!ELEMENT email (#PCDATA)><!ELEMENT description (#PCDATA)><!ELEMENT date (#PCDATA)><!ELEMENT country (#PCDATA)><!ELEMENT city (#PCDATA)><!ELEMENT bio (#PCDATA)><!ELEMENT affiliation (#PCDATA)><!ELEMENT address (#PCDATA)><!ELEMENT acronym (#PCDATA)><!ELEMENT acm_profile_id (#PCDATA)><!ELEMENT acm_doi (#PCDATA)>]>
<event>
  <event_details>
    <title>SPLASH 2020</title>
    <acronym>SPLASH 2020</acronym>
    <event_type type="conference"/>
    <start_date>2020/11/15</start_date>
    <end_date>2020/11/21</end_date>
    <location>
      <facility_name>Online</facility_name>
      <address>undefined</address>
      <city>Online Conference</city>
      <country>undefined</country>
    </location>
    <description>Welcome to SPLASH 2020, the ACM SIGPLAN conference on Systems, Programming, Languages, and Applications: Software for Humanity. SPLASH embraces all aspects of software construction and delivery, to make it the premier conference on the applications of programming languages—at the intersection of programming languages and software engineering. SPLASH takes place Sunday November 15th to Friday 20th. 
NEW: Watch a quick 6-minute instructional video on How to Attend SPLASH 2020 here: https://www.youtube.com/watch?v=bFiiuIEBG5I 
VIRTUAL SPLASH has three main streams: 
 
 SPLASH-I for OOPSLA and ECOOP research papers; 
 SPLASH-II for REBASE industry-oriented talks; 
 SPLASH-III for the major co-located events: GPCE/SLE on Sunday/Monday; Onward! Papers and Essays on Tuesday; SAS/DLS on Wednesday/Thursday; and OOPSLA research papers on Friday. 
 
MIRRORING In what we think is world first, SPLASH will do 12 hour mirroring, each conference days will be exactly 12 hours long with every single talk scheduled to repeat with a 12 hour delay. Therefore: whatever YOUR time zone happens to be, you can attend SPLASH during any convenient 12 hour block. For example: Alex from New Zealand plans to attend between 8am and 8pm NZ Standard Time; Jan from Czechia plans to attend between 8am and 8pm Central European Time, while Hridesh from Iowa plans to attend between 9am and 9pm Central Daylight Time! 
Workshops will take place outside the main three streams in virtual rooms SPLASH IV-VI. Please consult this table for details and login to SPLASH Clowdr to enter these rooms:  
 
  
   
    
    
   VMIL11/17 
    
    
    
   
  
  
   
    
    
   NSAD11/17 
    
    
    Tutorials11/20  
   
   
    
    
   LIVE11/7 
    
    
    SPLASH-E 11/20  
   
   
    
   HILT11/16 
   HILT11/17 
    
   TAPAS11/19 
    DocSymp 11/20  
   
   
   LPOP11/15 
   REBLS11/16 
    AGERE11/17 
   HATRA11/18 
   HATRA11/19 
   PLATEAU11/20 
   
  
 


 
SPLASH has multiple keynotes and invited industrial talks. These talks are followed by Ask Me Anything questions where you can engage with our speakers.</description>
    <url>https://2020.splashcon.org</url>
    <url_link_display>SPLASH 2020</url_link_display>
    <persons>
      <person>
        <role>General Chair in Organizing Committee, Committee Member in Steering Committee</role>
        <sort_key>1</sort_key>
        <first_name>Hridesh</first_name>
        <last_name>Rajan</last_name>
        <affiliation>Iowa State University, USA</affiliation>
        <bio>Hridesh Rajan is a Professor and Chair of Computer Science at Iowa State University, where he has been since 2005. Professor Rajan earned his MS and Ph.D. from the University of Virginia in 2004 and 2005 respectively. Professor Rajan’s recent research and educational activities are aimed at decreasing the barrier to entry to data-driven sciences to broaden participation. His work on the Boa project is aimed at the invention and refinement of programming languages and cyberinfrastructures that democratize data-driven science &amp;amp; engineering, including software engineering. His work on the Midwest Big Data Summer School is experimenting with broadly accessible data science curricula. Professor Rajan was the founding general chair of the Midwest Big Data Summer School. Professor Rajan’s research interests also include programming language design and implementation, and software engineering. He leads two research projects: Panini, whose goals are to enable modular reasoning about concurrent programs, and Boa that was established in Summer 2012 as an end-to-end infrastructure for analyzing large-scale software repositories and other open data sets. Professor Rajan is the director of the Laboratory for Software Design at Iowa State University, director of graduate admissions and recruitment for the Department of Computer Science. He serves as the department chair of the Department of Computer Science and served as the Professor-In-Charge of the Data Science education programs at Iowa State University from 2017-2019, and chair of the information technology committee for the university from 2015-2019. Professor Rajan served on the steering committee of the Midwest Big Data Hub, a consortium of universities in the Midwest region of the United States focused on promoting data science activities. Professor Rajan is a recipient of the National Science Foundation CAREER award in 2009, LAS Award for Early Achievement in Research in 2010, a Big-12 Fellowship in 2012. He is a 2018-19 Fulbright U.S. Scholar, a distinguished member of the ACM, and a member of IEEE, and AAAS. He is also the inaugural holder of the Kingland Professorship in the Department of Computer Science.</bio>
        <homepage_url>https://hridesh.github.io</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/hrideshrajan/f57a0842-20af-4fd4-b79f-5d673c2c485c/small.jpg</picture_url>
        <person_id>hrideshrajan</person_id>
      </person>
      <person>
        <role>Chair in Steering Committee</role>
        <sort_key>2</sort_key>
        <first_name>Eelco</first_name>
        <last_name>Visser</last_name>
        <affiliation>Delft University of Technology, Netherlands</affiliation>
        <bio>Eelco Visser is Antoni van Leeuwenhoek Professor of Computer Science at Delft University of Technology. He received a master’s and doctorate in computer science from the University of Amsterdam in 1993 and 1997, respectively. Previously he served as postdoc at the Oregon Graduate Institute, as Assistant Professor at Utrecht University, and as Associate Professor at TU Delft. 
His research interests include programming languages, software language engineering, domain-specific programming languages, program transformation, syntax definition, and parsing. With his students he has designed and implemented the Spoofax language workbench, as well as many domain-specific languages, including DSLs for syntax definition (SDF2, SDF3), program transformation (Stratego), static semantics (NaBL, Statix), dynamic semantics (DynSem), software deployment (Nix), web application development (WebDSL), and mobile phone applications (mobl). In the language designer’s workbench project he is pursuing high-level declarative language definition that serves for language implementation and verification.</bio>
        <homepage_url>http://eelcovisser.org</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/eelcovisser/3df68e8e-fc37-4ca4-bf4e-132e3d32b392/small.jpg</picture_url>
        <person_id>eelcovisser</person_id>
      </person>
      <person>
        <role>OOPSLA Review Committee Chair in Organizing Committee, Committee Member in Steering Committee</role>
        <sort_key>3</sort_key>
        <first_name>David</first_name>
        <last_name>Grove</last_name>
        <affiliation>IBM Research</affiliation>
        <bio>I am a Distinguished Research Staff Member at the IBM T.J. Watson Research Center. I joined IBM Research in 1998 after completing my PhD at the University of Washington. I am a software systems researcher, working primarily on problems in programming language implementation and scalable runtime systems. 
I have contributed to a number of technical topics in programming language design and implementation including the analysis and optimization of object-oriented languages, virtual machine design and implementation, scalable runtime systems, Just-In-Time compilation, online feedback-directed optimization, and garbage collection.</bio>
        <homepage_url>http://researcher.watson.ibm.com/researcher/view.php?person=us-groved</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/davidgrove/5524049e-7d0a-4799-ad8c-93e1e76a77ec/small.jpg</picture_url>
        <person_id>davidgrove</person_id>
      </person>
      <person>
        <role>Virtualization Co-Chair in Organizing Committee</role>
        <sort_key>4</sort_key>
        <first_name>Steve</first_name>
        <last_name>Blackburn</last_name>
        <affiliation>Australian National University</affiliation>
        <bio>My research interests are centered on the challenge of making software run faster and more power-efficiently on modern hardware. My primary interests include: microarchitectural support for managed languages, fast and efficient garbage collection, and the design and implementation of virtual machines. As a backdrop to this I have a longstanding interest in role of sound methodology and infrastructure in successful research innovation.</bio>
        <homepage_url>http://users.cecs.anu.edu.au/~steveb/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/steveblackburn/1deee732-405d-4403-a974-a418751399c2/small.jpg</picture_url>
        <person_id>steveblackburn</person_id>
      </person>
      <person>
        <role>Virtualization Co-Chair in Organizing Committee</role>
        <sort_key>5</sort_key>
        <first_name>Alex</first_name>
        <last_name>Potanin</last_name>
        <affiliation>Victoria University of Wellington</affiliation>
        <bio>I am an Associate Professor in the School of Engineering and Computer Science at Victoria University of Wellington, New Zealand. 
I am originally from Moscow, Russia with a background in Mathematics. I have completed my PhD in programming languages in 2006 and took up a job as a Lecturer in Software Engineering at Victoria University of Wellington. During my studies, I took short breaks to work as a Visiting Researcher at Purdue University, and Software Engineer at two Wellington start-ups. I spent 2013 on sabbatical at Carnegie Mellon University in Pittsburgh, PA, USA. I spent winter 2019/2020 on sabbatical at Kyoto University in Japan.</bio>
        <homepage_url>http://homepages.ecs.vuw.ac.nz/~alex/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/alexpotanin/614f887b-90a3-4626-b67d-fa63309b44c8/small.jpg</picture_url>
        <person_id>alexpotanin</person_id>
      </person>
      <person>
        <role>Virtualization Co-Chair in Organizing Committee, Committee Member in Steering Committee</role>
        <sort_key>6</sort_key>
        <first_name>Jan</first_name>
        <last_name>Vitek</last_name>
        <affiliation>Northeastern University, USA / Czech Technical University, Czechia</affiliation>
        <bio>Jan Vitek is a Professor of Computer Science at Northeastern University. Dr. Vitek was born in Czechoslovakia and educated in Switzerland. Over the years, he worked on topics related to programming languages, their design, use, and implementation. With Noble and Potter, he proposed the notion of flexible alias control which became know as Ownership Types. He led the Ovm project which produced the first real-time Java virtual machine to be flight tested on a ScanEagle drone (he claims no one was harmed). Outcomes of this project include the Schism real-time garbage collector and the FijiVM – a production VM for embedded systems. More recently, he worked on dynamic languages, trying to make sense of JavaScript and to design a new language called, Thorn. Nowadays, he spends his time with statisticians and data scientists. Jan believes that his 2012 election as Chair of SIGPLAN was an accident; since has been busy trying to rock the boat to ensure this does not happen again. In his spare time, Jan enjoys organizing conferences and sitting on PCs (over 25 in the last decade). He founded the MOS (mobile objects), IWACO (alias control), STOP (gradual typing), and TRANSACT (transactional memory) workshop series. He was the first program chair of VEE and chaired ESOP, ECOOP, Coordination and TOOLS. He was the general chair of PLDI (in Beijing!), ISMM and LCTES. He may still be sitting on the steering committees of ECOOP, JTRES, ICFP, OOPLSA, POPL, PLDI, LCTES, ESOP.</bio>
        <homepage_url>http://janvitek.org</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/janvitek/213b9734-8942-47ea-933d-6ffad4bb1ee6/small.jpg</picture_url>
        <person_id>janvitek</person_id>
      </person>
      <person>
        <role>Onward! Papers Chair in Organizing Committee, Committee Member in Steering Committee</role>
        <sort_key>7</sort_key>
        <first_name>Stephen</first_name>
        <last_name>Kell</last_name>
        <affiliation>University of Kent</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.kent.ac.uk/people/staff/srk21</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/stephenkell/53088184-3e8c-4a2c-b34f-b2a290cff411/small.jpg</picture_url>
        <person_id>stephenkell</person_id>
      </person>
      <person>
        <role>Onward! Essays Chair in Organizing Committee</role>
        <sort_key>8</sort_key>
        <first_name>Didier</first_name>
        <last_name>Verna</last_name>
        <affiliation>EPITA / LRDE</affiliation>
        <bio>Didier Verna has a Ph.D. and an habilitation in Computer Science, and is currently working as a professor for EPITA, a private Computer Science university located in Paris. He gives or has given lectures on Operating Systems, Computer Graphics, Object-Oriented, Functional Programming and Typesetting. His main research interests are multi-paradigm approaches to genericity and performance. 
Didier Verna is the president of the European Lisp Symposium steering committee and serves or has served as a program committee member in various conferences (International Lisp Conference, European Lisp Symposium, Dynamic Languages Symposium, ACM Symposium on Applied Computing, Onward!, Context-Oriented Programming workshop etc. ). 
Didier Verna is also quite involved in free software: he was one of the core maintainers of XEmacs for more than 15 years, a contributor to Gnus and BBDB, and an occasional contributor to other Free Software projects (the GNU Autotools most notably; he was one of the technical reviewers for the “Goat Book”). He is the author of several LaTeX packages and Common Lisp libraries. 
All of this is in fact half-true: two days a week, Didier Verna drops his scientific hat and wears the semi-professional Jazz musician one instead (he has released 3 albums with his quartet). He also is a certified Aikido teacher, and gives coaching sessions on the theme “Aikido and Conflict Management” for large companies.</bio>
        <homepage_url>https://www.lrde.epita.fr/~didier</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/didierverna/854d6aef-85b1-4d6e-a0e3-fa0dc86e3927/small.jpg</picture_url>
        <person_id>didierverna</person_id>
      </person>
      <person>
        <role>Local Arrangements Chair in Organizing Committee</role>
        <sort_key>9</sort_key>
        <first_name>Ravi</first_name>
        <last_name>Chugh</last_name>
        <affiliation>University of Chicago</affiliation>
        <bio>I am an Assistant Professor at the University of Chicago. I enjoy developing and deploying programming language technology — type systems, synthesis algorithms, and other program analysis techniques — for applications in software engineering and human-computer interaction.</bio>
        <homepage_url>http://people.cs.uchicago.edu/~rchugh</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/ravichugh/ea931b20-b1e1-4e07-b209-ba0b568e315d/small.jpg</picture_url>
        <person_id>ravichugh</person_id>
      </person>
      <person>
        <role>Rebase Co-chair in Organizing Committee</role>
        <sort_key>10</sort_key>
        <first_name>Satish</first_name>
        <last_name>Chandra</last_name>
        <affiliation>Facebook, USA</affiliation>
        <bio>Satish Chandra obtained a PhD from the University of Wisconsin-Madison in 1997, and a B.Tech from the Indian Institute of Technology-Kanpur in 1991, both in computer science. From 1997 to 2002, he was a member of technical staff at Bell Laboratories, where his research focused on program analysis, domain-specific languages, and data-communication protocols. From 2002 to 2013, he was a research staff member at IBM Research, where his research focused on bug finding and verification, software synthesis, and test automation. His work on bug finding shipped in IBM’s Java static analysis product, and his work on test automation was adopted in IBM’s testing services offering. From 2013 to 2016, he worked at Samsung Research America, where he led the advanced programming tools research team. His work on memory profiling of web apps was included in Samsung’s Tizen IDE. In 2016, he started working at Facebook. He is an ACM Distinguished Scientist.</bio>
        <homepage_url>https://sites.google.com/site/schandraacmorg/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/satishchandra/6f67adc9-cd3d-4d0b-ad13-5bb13fd21834/small.jpg</picture_url>
        <person_id>satishchandra</person_id>
      </person>
      <person>
        <role>Rebase Co-chair in Organizing Committee</role>
        <sort_key>11</sort_key>
        <first_name>Yu David</first_name>
        <last_name>Liu</last_name>
        <affiliation>State University of New York (SUNY) Binghamton</affiliation>
        <bio>I am a Professor at State University of New York (SUNY) at Binghamton. I am interested in programming languages, computer systems, and software engineering. My current research focuses are energy-aware programming languages, data-intensive software, programming unmanned aerial vehicles, and type systems. I received my Ph.D. in Computer Science from the Johns Hopkins University, in 2007.</bio>
        <homepage_url>http://www.cs.binghamton.edu/~davidl</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/yudavidliu/1da5367f-6c86-4df7-859d-ca63bc2a178b/small.jpg</picture_url>
        <person_id>yudavidliu</person_id>
      </person>
      <person>
        <role>PLMW Co-Chair in Organizing Committee</role>
        <sort_key>12</sort_key>
        <first_name>Karim</first_name>
        <last_name>Ali</last_name>
        <affiliation>University of Alberta</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://karimali.ca</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/karimali/460ecc0b-764d-462b-a93e-66a3270d72ef/small.jpg</picture_url>
        <person_id>karimali</person_id>
      </person>
      <person>
        <role>PLMW Co-Chair in Organizing Committee</role>
        <sort_key>13</sort_key>
        <first_name>Jonathan</first_name>
        <last_name>Bell</last_name>
        <affiliation>Northeastern University, USA</affiliation>
        <bio>Jon is an Assistant Professor directing research in Software Engineering and Software Systems at Northeastern University. His research makes it easier for developers to create reliable and secure software by improving software testing and program analysis. Jon’s work on accelerating software testing has been recognized with an ACM SIGSOFT Distinguished Paper Award (ICSE ’14 – Unit Test Virtualization with VMVM), and was the basis for an industrial collaboration with Electric Cloud. His program analysis research has resulted in several widely adopted runtime systems for the JVM, including the Phosphor taint tracking system (OOPSLA ’14) and CROCHET checkpoint/rollback tool (ECOOP ’18). His research has been funded by the NSA and the NSF, and he is the recipient of the NSF CAREER award. At George Mason, Jon taught courses in distributed systems, web development, and program analysis. His teaching at GMU has been recognized with a departmental award. Jon serves on a variety of program committees and was recently co-chair of the PLDI 2020 Artifact Evaluation Committee. As part of his efforts to broaden the participation of underrepresented groups in computing, Jon co-organizes the PL/SE mentoring workshop at SPLASH (in 2017, 2018, 2019 and 2020).</bio>
        <homepage_url>http://jonbell.net/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/jonathanbell/1ef3641d-0ed6-4021-aab6-b13b53962e3d/small.jpg</picture_url>
        <person_id>jonathanbell</person_id>
      </person>
      <person>
        <role>PLMW Co-Chair in Organizing Committee</role>
        <sort_key>14</sort_key>
        <first_name>Malavika</first_name>
        <last_name>Samak</last_name>
        <affiliation>CSAIL, MIT</affiliation>
        <bio>I am a Postdoctoral Associate working at CSAIL, MIT. I received my PhD from the Department of Computer Science and Automation, IISc Bangalore and was supported by a Google India PhD fellowship. For my doctoral dissertation, I designed and implemented techniques to address the problem of automatically synthesizing clients for detecting concurrency bugs in multithreaded libraries. My research interests are in software engineering and programming languages.</bio>
        <homepage_url>https://sites.google.com/site/malavikasamak/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/malavikasamak/ce059484-133f-4009-8f2d-de4df3abb83f/small.jpg</picture_url>
        <person_id>malavikasamak</person_id>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>15</sort_key>
        <first_name>Mehdi</first_name>
        <last_name>Bagherzadeh</last_name>
        <affiliation>Oakland University, USA</affiliation>
        <bio>Assistant Professor, Department of Computer Science and Engineering</bio>
        <homepage_url>https://mbagherz.bitbucket.io/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/mehdibagherzadeh/95dc6f53-51a0-4bf1-b822-7bbe8c4d223a/small.jpg</picture_url>
        <person_id>mehdibagherzadeh</person_id>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>16</sort_key>
        <first_name>Neville</first_name>
        <last_name>Grech</last_name>
        <affiliation>University of Malta</affiliation>
        <bio>I am a Lecturer at the University of Malta. My expertise is focused on program analysis, applied to security and other high-level applications. My research work has been recently highlighted by ACM SIGPLAN and Communications of the ACM. I am also interested in the areas of energy efficient systems, smart contracts, semantics and generative programming. My research tools include decompilers and security analyzers for the Ethereum platform (Gigahorse) and Java pointer and taint analysis frameworks (Doop, P/Taint and HeapDL). Previously, I was Reach High Fellow at the University of Athens, a Senior Research Associate at the University of Bristol, and have worked in industry as a Data Scientist and Software Engineer. I hold a PhD from the University of Southampton.</bio>
        <homepage_url>http://www.nevillegrech.com</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/nevillegrech/e0405613-3240-4ef2-a51f-cb7536870dc5/small.jpg</picture_url>
        <person_id>nevillegrech</person_id>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>17</sort_key>
        <first_name>Ali</first_name>
        <last_name>Jannesari</last_name>
        <affiliation>Iowa State University</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://www.eecs.berkeley.edu/~jannesari/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/alijannesari/bc7c4a53-b541-49d8-a2c3-04e4a5f18047/small.jpg</picture_url>
        <person_id>alijannesari</person_id>
      </person>
      <person>
        <role>Student Research Competition Co-Chair in Organizing Committee</role>
        <sort_key>18</sort_key>
        <first_name>Sasa</first_name>
        <last_name>Misailovic</last_name>
        <affiliation>University of Illinois at Urbana-Champaign, USA</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://misailo.cs.illinois.edu/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/sasamisailovic/6e3299c7-e0f5-4e78-a5f3-7ea49e488545/small.jpg</picture_url>
        <person_id>sasamisailovic</person_id>
      </person>
      <person>
        <role>Student Research Competition Co-Chair in Organizing Committee</role>
        <sort_key>19</sort_key>
        <first_name>Julia</first_name>
        <last_name>Rubin</last_name>
        <affiliation>University of British Columbia, Canada</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.ece.ubc.ca/~mjulia/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/juliarubin/5846079d-0c90-4d9a-8f16-eef07002e37d/small.jpg</picture_url>
        <person_id>juliarubin</person_id>
      </person>
      <person>
        <role>Publicity Chair in Organizing Committee</role>
        <sort_key>20</sort_key>
        <first_name>Hitesh</first_name>
        <last_name>Sajnani</last_name>
        <affiliation>Microsoft </affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.ics.uci.edu/~hsajnani/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/hiteshsajnani/01055225-912e-4ea5-865b-e5e0e01767c2/small.jpg</picture_url>
        <person_id>hiteshsajnani</person_id>
      </person>
      <person>
        <role>Web Chair in Organizing Committee</role>
        <sort_key>21</sort_key>
        <first_name>Rangeet</first_name>
        <last_name>Pan</last_name>
        <affiliation>Iowa State University, USA</affiliation>
        <bio>Rangeet Pan is a Ph.D. student at Iowa State University. His research interests include program analysis, machine learning, and software engineering. He has published works at ESEC/FSE and ICSE.</bio>
        <homepage_url>https://rangeetpanisu.web.app/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/rangeetpan/3f0551cd-7e73-4053-bb36-66f8d05daae5/small.jpg</picture_url>
        <person_id>rangeetpan</person_id>
      </person>
      <person>
        <role>Student Volunteer Co-Chair in Organizing Committee</role>
        <sort_key>22</sort_key>
        <first_name>Robert</first_name>
        <last_name>Dyer</last_name>
        <affiliation>University of Nebraska - Lincoln</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://go.unl.edu/rdyer</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/robertdyer/774d6fd8-9a08-4c37-9113-f0bc0c5fb833/small.jpg</picture_url>
        <person_id>robertdyer</person_id>
      </person>
      <person>
        <role>Student Volunteer Co-Chair in Organizing Committee</role>
        <sort_key>23</sort_key>
        <first_name>Samantha Syeda</first_name>
        <last_name>Khairunnesa</last_name>
        <affiliation>Iowa State University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://web.cs.iastate.edu/~sammy/</homepage_url>
        <picture_url>https://2020.splashcon.org/getProfileImage/samanthasyedakhairunnesa/23aa8334-ebf0-4967-b8ab-6d4cbf1509c5/small.jpg</picture_url>
        <person_id>samanthasyedakhairunnesa</person_id>
      </person>
      <person>